import os
from uuid import UUID
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem
from reportlab.lib.colors import HexColor
from datetime import datetime, timezone

REPORTS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "uploads", "reports")


async def generate_meeting_report(
    meeting_id: UUID,
    title: str,
    summary: str,
    transcript: str,
    speakers: list,
    key_decisions: list,
    action_items: list,
    insights: list,
    duration: int,
    created_at: datetime,
) -> str:
    os.makedirs(REPORTS_DIR, exist_ok=True)
    filepath = os.path.join(REPORTS_DIR, f"meeting_{meeting_id}.pdf")

    doc = SimpleDocTemplate(filepath, pagesize=A4,
                            rightMargin=72, leftMargin=72,
                            topMargin=72, bottomMargin=72)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "CustomTitle", parent=styles["Title"],
        fontSize=24, textColor=HexColor("#1a1a2e"), spaceAfter=30,
    )
    heading_style = ParagraphStyle(
        "CustomHeading", parent=styles["Heading2"],
        fontSize=16, textColor=HexColor("#16213e"), spaceBefore=20, spaceAfter=10,
    )
    body_style = ParagraphStyle(
        "CustomBody", parent=styles["Normal"],
        fontSize=11, leading=16, spaceAfter=12,
    )
    meta_style = ParagraphStyle(
        "Meta", parent=styles["Normal"],
        fontSize=10, textColor=HexColor("#666666"), spaceAfter=6,
    )

    story = []
    story.append(Paragraph(f"Meeting Report: {title or 'Untitled'}", title_style))
    story.append(Paragraph(f"Date: {created_at.strftime('%B %d, %Y at %I:%M %p') if created_at else 'N/A'}", meta_style))
    story.append(Paragraph(f"Duration: {duration // 60}m {duration % 60}s", meta_style))
    story.append(Spacer(1, 20))

    story.append(Paragraph("Executive Summary", heading_style))
    story.append(Paragraph(summary or "No summary available.", body_style))
    story.append(Spacer(1, 10))

    if speakers:
        story.append(Paragraph("Speakers", heading_style))
        speaker_list = [ListItem(Paragraph(s, body_style)) for s in speakers]
        story.append(ListFlowable(speaker_list, bulletType="bullet", leftIndent=20))
        story.append(Spacer(1, 10))

    if key_decisions:
        story.append(Paragraph("Key Decisions", heading_style))
        decisions_list = [ListItem(Paragraph(d, body_style)) for d in key_decisions]
        story.append(ListFlowable(decisions_list, bulletType="bullet", leftIndent=20))
        story.append(Spacer(1, 10))

    if action_items:
        story.append(Paragraph("Action Items", heading_style))
        actions_list = [ListItem(Paragraph(a, body_style)) for a in action_items]
        story.append(ListFlowable(actions_list, bulletType="bullet", leftIndent=20))
        story.append(Spacer(1, 10))

    if insights:
        story.append(Paragraph("Key Insights", heading_style))
        insights_list = [ListItem(Paragraph(i, body_style)) for i in insights]
        story.append(ListFlowable(insights_list, bulletType="bullet", leftIndent=20))
        story.append(Spacer(1, 10))

    story.append(Paragraph("Full Transcript", heading_style))
    transcript_text = transcript or "No transcript available."
    for line in transcript_text.split("\n"):
        story.append(Paragraph(line, body_style))

    story.append(Spacer(1, 30))
    story.append(Paragraph(f"Generated by Second Memory on {datetime.now(timezone.utc).strftime('%B %d, %Y')}", meta_style))

    doc.build(story)
    return filepath
